client/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, re_path
from django.views.generic import TemplateView
from onfig.view import MediaView


media_path = settings.MEDIA_URL.replace(settings.FORCE_SCRIPT_NAME, '')
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    re_path(r'^contact$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    re_path(r'^privacy$', TemplateView.as_view(template_name='privacy.html'), name="privacy"),

    # protected file upload
    re_path(r'^' + media_path + '(?P<file_name>.+)$', MediaView.as_view(), name="media"),

    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^files/', include('files.urls', namespace='files')),
    re_path(r'^simulations/', include('simulations.urls', namespace='simulations')),
]

client/files/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^models$',
        views.CellmlModelListView.as_view(),
        name='model_list',
    ),

    re_path(
        r'^models/new$',
        views.CellmlModelCreateView.as_view(),
        name='create_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/edit$',
        views.CellmlModelUpdateView.as_view(),
        name='edit_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)$',
        views.CellmlModelDetailView.as_view(),
        name='model_detail',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/delete$',
        views.CellmlModelDeleteView.as_view(),
        name='delete_model',
    ),

]
app_name = 'files'

client/simulations/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^$',
        views.SimulationListView.as_view(),
        name='simulation_list',
    ),


    re_path(
        r'^new$',
        views.SimulationCreateView.as_view(),
        name='create_simulation',
    ),

    re_path(
        r'^(?P<pk>\d+)/edit$',
        views.SimulationEditView.as_view(),
        name='simulation_edit',
    ),

    re_path(
        r'^(?P<pk>\d+)/template$',
        views.SimulationCreateView.as_view(),
        name='simulation_template',
    ),

    re_path(
        r'^(?P<pk>\d+)/result$',
        views.SimulationResultView.as_view(),
        name='simulation_result',
    ),

    re_path(
        r'^(?P<pk>\d+)/version$',
        views.SimulationVersionView.as_view(),
        name='simulation_version',
    ),

    re_path(
        r'^(?P<pk>\d+)/delete$',
        views.SimulationDeleteView.as_view(),
        name='simulation_delete',
    ),

    re_path(
        r'^(?P<pk>\d+)/restart$',
        views.RestartSimulationView.as_view(),
        name='simulation_restart',
    ),
    re_path(
        r'^status/(?P<update>(\w+))(?P<pks>(/\d+){1,})(?:/)?$',
        views.StatusSimulationView.as_view(),
        name='simulation_status',
    ),
    re_path(
        r'^(?P<pk>\d+)/data$',
        views.DataSimulationView.as_view(),
        name='simulation_data',
    ),
    re_path(
        r'^(?P<pk>\d+)/spreadsheet$',
        views.SpreadsheetSimulationView.as_view(),
        name='simulation_spreadsheet',
    ),

]
app_name = 'simulations'

client/simulations/models.py
import math
import os

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext as _
from files.models import CellmlModel, IonCurrent


@deconstructible
class StrictlyGreaterValidator(MinValueValidator):
    """
    Validator expectign value to be strictly greater (not equal).
    """
    message = _('Ensure this value is greater than %(limit_value)s.')

    def compare(self, a, b):
        return a <= b


class Simulation(models.Model):
    """
    Main simulation model
    """
    class Status(models.TextChoices):
        NOT_STARTED = "NOT_STARTED"
        INITIALISING = "INITIALISING"
        RUNNING = "RUNNING"
        SUCCESS = "SUCCESS"
        FAILED = "FAILED"

    class IonCurrentType(models.TextChoices):
        PIC50 = 'pIC50', 'pIC50'
        IC50 = 'IC50', 'IC50'

    class IonCurrentUnits(models.TextChoices):
        negLogM = '-log(M)', '-log(M)'
        M = 'M', 'M'
        µM = 'µM', 'µM'
        nM = 'nM', 'nM'

    def conversion(choice):
        if choice == Simulation.IonCurrentUnits.M:
            return lambda c: - math.log10(c)
        elif choice == Simulation.IonCurrentUnits.µM:
            return lambda c: - math.log10(1e-6 * c)
        elif choice == Simulation.IonCurrentUnits.nM:
            return lambda c: - math.log10(1e-9 * c)
        else:
            return lambda c: c

    class PkOptions(models.TextChoices):
        compound_concentration_range = 'compound_concentration_range', 'Compound Concentration Range'
        compound_concentration_points = 'compound_concentration_points', 'Compound Concentration Points'
        pharmacokinetics = 'pharmacokinetics', 'Pharmacokinetics'

    status = models.CharField(choices=Status.choices, max_length=255, blank=True, default=Status.NOT_STARTED)
    title = models.CharField(max_length=255, help_text="A short title to identify this simulation.")
    notes = models.TextField(blank=True, default='',
                             help_text="Any notes related to this simulation. Please note: These will also be visible "
                                       "to admin users.")
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)

    model = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=CellmlModel)
    pacing_frequency = models.FloatField(default=1.0, help_text="(in Hz) Frequency of pacing (between 0.05 and 5).",
                                         validators=[MinValueValidator(0.05), MaxValueValidator(5)])
    maximum_pacing_time = models.FloatField(default=5, help_text="(in mins) Maximum pacing time (between 0 and 120).",
                                            validators=[StrictlyGreaterValidator(0), MaxValueValidator(120)])

    ion_current_type = models.CharField(choices=IonCurrentType.choices, max_length=255, help_text="Ion current type.")
    ion_units = models.CharField(choices=IonCurrentUnits.choices, max_length=255, help_text="Ion current units.")

    pk_or_concs = models.CharField(max_length=255, choices=PkOptions.choices, default='compound_concentration_range')
    minimum_concentration = models.FloatField(blank=True, null=True, default=0, help_text="(in µM) at least 0.",
                                              validators=[MinValueValidator(0)])
    maximum_concentration = models.FloatField(blank=True, null=True, default=100,
                                              help_text="(in µM) > minimum_concentration.",
                                              validators=[MinValueValidator(0)])
    intermediate_point_count = models.CharField(
        max_length=255, choices=[(str(i), str(i)) for i in range(11)], default='4', blank=True,
        help_text='Count of plasma concentrations between the minimum and maximum (between 0 and 10).'
    )
    intermediate_point_log_scale = models.BooleanField(default=True, blank=True,
                                                       help_text='Use log scale for intermediate points.')
    PK_data = models.FileField(blank=True, help_text="File format: tab-seperated values (TSV). Encoding: UTF-8\n"
                                                     "Column 1 : Time (hours)\nColumns 2-31 : Concentrations (µM).")
    progress = models.CharField(max_length=255, blank=True, default='Initialising..')
    ap_predict_last_update = models.DateTimeField(blank=True, default=timezone.now)
    ap_predict_call_id = models.CharField(max_length=255, blank=True)
    api_errors = models.CharField(max_length=255, blank=True)
    messages = models.JSONField(blank=True, null=True)
    q_net = models.JSONField(blank=True, null=True)
    voltage_traces = models.JSONField(blank=True, null=True)
    voltage_results = models.JSONField(blank=True, null=True)
    pkpd_results = models.JSONField(blank=True, null=True)
    STDOUT = models.JSONField(blank=True, null=True)
    version_info = models.JSONField(blank=True, null=True)

    class Meta:
        unique_together = ('title', 'author')
        ordering = ('-created_at', 'model')

    def __str__(self):
        return self.title


class SimulationIonCurrentParam(models.Model):
    """
    Ion current parameter for a given simulation
    """
    simulation = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=Simulation, blank=True)
    ion_current = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=IonCurrent)
    # can't validate as restriction only if IC50 selected. Form javascript should validate
    current = models.FloatField(blank=True, null=True, help_text="> 0 for IC50.")
    hill_coefficient = models.FloatField(default=1, help_text="Between 0.1 and 5.", blank=True,
                                         validators=[MinValueValidator(0), MaxValueValidator(5)])
    saturation_level = models.FloatField(default=0, validators=[MinValueValidator(0)], blank=True,
                                         help_text="Level of peak current relative to control at a very large compound "
                                                   "concentration (between 0 and 1).\n- For an inhibitor this is in the"
                                                   " range 0% (default) to <100% (compound has no effect).\n- For an "
                                                   "activator Minimum > 100% (no effect) to Maximum 500% (as a "
                                                   "guideline).")
    spread_of_uncertainty = models.FloatField(blank=True, null=True,
                                              validators=[StrictlyGreaterValidator(0), MaxValueValidator(2)],
                                              help_text="Spread of uncertainty (between 0 and 2).\nDefaults are "
                                                        "estimates based on a study by Elkins et all.\nIdeally all "
                                                        "these numbers would be replaced based on the spread you "
                                                        "observe in fitted pIC50s.")

    def __str__(self):
        return str(self.ion_current) + " - " + str(self.simulation)


class CompoundConcentrationPoint(models.Model):
    """
    Concentration point for a given simulation
    """
    simulation = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=Simulation, blank=True)
    concentration = models.FloatField(validators=[MinValueValidator(0), ], help_text="(in µM) at least 0.")

    class Meta:
        ordering = ('concentration', )

    def __str__(self):
        return str(self.simulation) + " - " + str(self.concentration)


@receiver(models.signals.post_delete, sender=Simulation)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `Simulation` object is deleted.
    """
    if instance.PK_data:
        if os.path.isfile(instance.PK_data.path):
            os.remove(instance.PK_data.path)

client/templates/simulations/simulation.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create simulation - {% endblock title %}

{% block content %}
<h1>Create simulation.</h1>

  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ion_formset.management_form}}
    {{concentration_formset.management_form}}
    {{form.non_field_errors}}
    <fieldset>
    <legend>Info</legend>
      <p><label for="id_title">Title:</label>{{ form.title.errors }} {{ form.title }}</p>
      <p><label for="id_notes">Additional notes:</label><br/> {{ form.notes.errors }} {{ form.notes }} <span class="helptext">{{ form.help_text|safe }}</span></p>
    </fieldset>

    <fieldset>
    <legend>Cellml Model</legend>
      <p>{{ form.model.errors }} {{ form.model }} or <a href="{% url 'files:create_model' %}">Upload a new annotated CellML model</a></p>
    </fieldset>

    <fieldset>
    <legend>Pacing details</legend>
      <p>{{ form.pacing_frequency.label_tag }} {{ form.pacing_frequency.errors }} {{ form.pacing_frequency }} <span class="helptext">{{ form.pacing_frequency.help_text }}</span></p> 
      <p>{{ form.maximum_pacing_time.label_tag }} {{ form.maximum_pacing_time.errors }} {{ form.maximum_pacing_time }} <span class="helptext">{{ form.maximum_pacing_time.help_text|safe }}</span></p>
    </fieldset>

    <fieldset>
    <legend>Ion Channel Current Inhibitory Concentrations</legend>
      <table class="ioncurrent-formset" id="ioncurrent-formset">
        {% with firstline=ion_formset|first %}
          <thead><tr><th colspan="3" title="{{firstline.current.help_text}}">Ion Current<img src="{% static 'images/info.png' %}" class="infobutton"> {{form.ion_current_type}} {{form.ion_units}}</th>
                     <th title="{{firstline.hill_coefficient.help_text}}">Hill <br/>Coefficient<img src="{% static 'images/info.png' %}" class="infobutton"> </th>
                     <th title="{{firstline.saturation_level.help_text}}">Saturation <br/>Level (%)<img src="{% static 'images/info.png' %}" class="infobutton"> </th>
                     <th title="{{firstline.spread_of_uncertainty.help_text}}"><input type="checkbox" id="enable_spread_of_uncertainty">Spread of <br/>Uncertainty<img src="{% static 'images/info.png' %}" class="infobutton"> </th>
                     <th>Channel <br/>protein</th><th>Gene</th><th id="ion-description-header">Description</th></tr></thead>
        {% endwith %}
        <tbody>
{{ion_formset.non_field_errors}}
          {% for ion_form in ion_formset %}
            {{ion_form.non_field_errors}}
            <tr><td id="currentname"><input type="hidden" name="ion-{{ forloop.counter0 }}-models" value="{% for ion in ion_form.initial.models %}{{ion}},{% endfor %}" class="used-in-models" title="" id="id_ion-{{ forloop.counter0 }}-models">{{ion_form.initial.ion_current}} {{ion_form.ion_current.as_hidden}}{{ion_form.ion_current.errors}}</td>
                <td id="currentval">{{ion_form.current.errors}}{{ion_form.current}}</td><td class="ion-units">-log(m)</td>
                <td>{{ion_form.hill_coefficient.errors}}{{ion_form.hill_coefficient}}</td>
                <td>{{ion_form.saturation_level.errors}}{{ion_form.saturation_level}}</td>
                <td>{{ion_form.spread_of_uncertainty.errors}}{{ion_form.default_spread_of_uncertainty.errors}}{{ion_form.spread_of_uncertainty}}{{ion_form.default_spread_of_uncertainty.as_hidden}}</td>
                <td>{{ion_form.initial.channel_protein.errors}}{{ion_form.initial.channel_protein|safe}}</td>
                <td><em>{{ion_form.initial.gene}}</em></td>
                <td>{{ion_form.initial.description}}</td></tr>
          {% endfor %}
          </tbody>
      </table>
    </fieldset>
   <fieldset>
    <legend>{% for radio in form.pk_or_concs%}{{radio}}{% endfor %}</legend>
           <div id="div_pk_or_concs_0">
               <p>{{ form.minimum_concentration.label_tag }} {{ form.minimum_concentration.errors }} {{ form.minimum_concentration }} <span class="helptext">{{ form.minimum_concentration.help_text }}</span></p>
               <p>{{ form.maximum_concentration.label_tag }} {{ form.maximum_concentration.errors }} {{ form.maximum_concentration }} <span class="helptext">{{ form.maximum_concentration.help_text }}</span></p>
               <p>{{ form.intermediate_point_count.label_tag }} {{ form.intermediate_point_count.errors }} {{ form.intermediate_point_count }} <span class="helptext">{{ form.intermediate_point_count.help_text }}</span></p>
               <p>{{ form.intermediate_point_log_scale.label_tag }} {{ form.intermediate_point_log_scale.errors }} {{ form.intermediate_point_log_scale }} <span class="helptext">{{ form.intermediate_point_log_scale.help_text }}</span></p>
           </div>
           <div id="div_pk_or_concs_1">
                   <div id="compound-concentration-points">
{{concentration_formset.non_field_errors}}
                   {% for concentration_form in concentration_formset %}
                       <div class="compound-concentration-point">
                           <input type="hidden"  class="compound-concentration-point-index" value="{{forloop.counter}}">
                           <span class="compound-concentration-point-index-text">{{concentration_form.non_field_errors}}{{forloop.counter|stringformat:"02d" }}. </span>{{concentration_form.concentration.errors}}{{concentration_form.concentration}} µM<br/>
                       </div>
                   {% endfor %}
                   </div>
                   <p><span id="add-row-concentration-points"> <a class="active" href="javascript:void(0)">add more points</a></span></p>
           </div>
           <div id="div_pk_or_concs_2">
               <p>{{ form.PK_data.label_tag }} {{ form.PK_data.errors }} {{ form.PK_data }} <span class="helptext">{{ form.PK_data.help_text }}</span></p>
           </div>
   </fieldset>
    <p>
    <button id="savebutton" type="submit">Run simulation</button>
    <button class="button" id="backbutton" title="Cancel">Cancel</button>
    </p>
  </form>
</div>
{% endblock content %}

client/templates/simulations/simulation_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete simulation{% endblock title %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the simulation "{{ object }}"?</p>
    <p><strong>This operation cannot be undone and the results will also be deleted.</strong></p>
    <button>Confirm</button>
    <button class="button" id="backbutton" title="Cancel">Cancel</button>
</form>

{% endblock %}

client/templates/simulations/simulation_data.html
{}

client/templates/simulations/simulation_header.html
{% load static %}
{% load ap_nimbus %}

{% can_edit object as can_edit %}
{% if can_edit%}

  {%if showView%}<a title="View result" href="{% url 'simulations:simulation_result' object.id %}" title="View result"><img src="{% static 'images/view.png' %}" alt="View"/></a>{%endif%}
  <a title="Edit this simulation info" href="{% url 'simulations:simulation_edit' object.id %}" title="Edit the information"><img src="{% static 'images/edit.png' %}" alt="Edit"/></a>
  <a title="Use simulation as template for a new simulation" href="{% url 'simulations:simulation_template' object.id %}" title="Use as a template to create a new simulation"><img src="{% static 'images/template.png' %}" alt="Use as template"/></a> 
  <span id="spreadsheetexport{{object.id}}" {%if 'SUCCESS' != object.status%}style="visibility: hidden; display: none"{%endif%}><a title="Export as spreadsheet (.xlsx)" href="{% url 'simulations:simulation_spreadsheet' object.id %}" title="Export as spreadsheet (.xlsx)"><img src="{% static 'images/spreadsheet.png' %}" alt="Export as spreadsheet (.xlsx)"/></a></span>
  <span id="restart{{object.id}}" {%if 'FAILED' != object.status%}style="visibility: hidden; display: none"{%endif%}><a title="Restart the simulation" href="{% url 'simulations:simulation_restart' object.id %}" title="Restart the simulation"><img src="{% static 'images/restart.png' %}" alt="Restart the simulation"/></a> </span>
  <a title="Delete this simulation and all results" href="{% url 'simulations:simulation_delete' object.id %}" title="Delete"><img src="{% static 'images/delete.png' %}" alt="Delete"/></a>
{% endif %}

client/templates/simulations/simulation_list.html
{% extends "base.html" %}
{% load static %}
{% load simulations %}


{% block title %}Simulations - {% endblock title %}

{% block content %}
  <section id="simulationgrouplist">
    <h2>Your simulations</h2>

    <p><a href="{% url 'simulations:create_simulation' %}" class="pointer">Create a new simulation</a></p>

  <table class="stripe row-border order-column" id="simulations_table" style="width:100%; overflow-wrap: break-word;">
      <thead>
        <tr>
          <th style="min-width: 250px; max-width: 250px; width: 250px;" id="title">Title</th>
          <th style="min-width: 45px; max-width: 45px; width: 45px;">Date</th>
          <th style="min-width: 148px; max-width: 148px; width: 148px;">Model</th>
          <th style="min-width: 80px; max-width: 80px; width: 80px;">Action</th>

{% ion_currents as all_currents %}
          <th colspan="2"  style="min-width: 70px; max-width: 70px; width: 70px;">Pacing</th>
          <th colspan="{{ all_currents|length|add:1 }}">Ion Channel Current Inhibitory Concentrations</th>
          <th colspan="2" style="min-width: 68px; max-width: 68px; width: 68px;">Compound Concentrations</th>
        </tr>
        <tr>
        <th colspan="4"></th>
        <th style="min-width: 34px; max-width: 35px; width: 35px;">Freq.</td><th  style="min-width: 35px; max-width: 35px; width: 35px;">Max Time</th>

        {% for cur in all_currents %}
          <th style="min-width: 40px; max-width: 40px;">{{ cur }}</th>
        {% endfor %}
        <th>Units</th>
        <th/><th/>
      </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
      <tr>
        <td><img class="progressIcon" id="progressIcon-{{object.pk}}" {%if object.status == "SUCCESS" %}src="{% static 'images/finished.gif' %}" title="Simulation completed succesfully."{% elif object.status == "FAILED" %}src="{% static 'images/failed.gif' %}" title="Simulation failed!"{% else %}src="{% static 'images/inprogress.gif' %}" title="Simulation in progress."{% endif %}/>
            <a href="{% url 'simulations:simulation_result' object.pk %}">{{object.title}}</a></td>
        <td>{{object.created_at|date:"Y/m/d" }}</td>
        <td><a href="{% url 'files:model_detail' object.model.pk %}">{{object.model}}</a></td>

        <td>{% include "./simulation_header.html" with showView=True%} </td>
        <td>{{object.pacing_frequency}} <em>Hz</em></td><td>{{object.maximum_pacing_time}} <em>mins</em></td>
        {% for cur in all_currents %}
        {% simulation_ion_current object cur as currentparam%}
            <td>{{ currentparam.current }}</td>
        {% endfor %}
        <td>{{object.ion_units}}<br/>({{object.ion_current_type}})</td>
        <td>{% short_field_name object.pk_or_concs %}</td>
        {%print_compound_concentrations object as inhconc %}
        <td title="{{ inhconc.0 }}">{{ inhconc.1 }}</td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
  </section>

{% endblock content %}

client/templates/simulations/simulation_result.html
{% extends "base.html" %}
{% load static %}
{% load simulations %}


{% block title %}Simulation result - {% endblock title %}

{% block content %}

<section id="simulationresults">
<h1 id="entityname"><a title="Back to simulations overview table" href="{% url 'simulations:simulation_list' %}" title="Back to simulations overview table"><img src="{% static 'images/back.png' %}" alt="Back"/></a>{% include "./simulation_header.html" %}Simulation: {{ object.title }}.</h1>
<small>Created <time>{{object.created_at}}</time> by <em>{{object.author.full_name}}</em>.</small>
{% if object.intermediate_point_log_scale %}<div id="intermediate_point_log_scale_set" style="display: none;"></div>{% endif %}
<div class="row">
  <div class="column">
  <fieldset>
    <legend><button type="button" class="graph-button" id="infoButton" disabled="">Info</button></legend>
    <table class="stripe dataTable">
      <tr class="odd"><td>Title</td><td>{{ object.title }}</td></tr>
       <tr class="even"><td>Model</td><td>{{ object.model }}</td></tr>
       <tr class="odd"><td>Pacing frequency</td><td>{{ object.pacing_frequency }} (Hz)</td></tr>
       <tr class="even"><td>Max pacing time</td><td>{{ object.maximum_pacing_time }} (mins)</td></tr>
       <tr class="odd"><td>{% print_field_name object.pk_or_concs %}</td><td>{% print_compound_concentrations object as inhconc %}{{ inhconc.0 }}</td></tr>
       <tr class="even"><td>Status</td><td><div id="progressbar-{{object.pk}}" class="progressbar progressbar-wide"><div class="progress-label"></div></div></td></tr>
    </table>
    <br/>
        <label>Ion Channel Current Inhibitory Concentrations</label><br/>
        <table class="stripe dataTable" id="ioncurrent-formset">
          <thead><tr><th>Ion Current</th>
                     <th>{{object.ion_current_type}}</th>
                     <th>Hill <br/>Coefficient</th>
                     <th>Saturation <br/>Level (%)</th>
                     <th>Spread of <br/>Uncertainty</th>
                 </tr>
          </thead>
          <tbody>
            {% ion_currents as all_currents %}
            {% for current in all_currents %}
            {% simulation_ion_current object current as currentparam %}
            <tr class="{% if forloop.counter|divisibleby:'2' %}even{% else %}odd{%endif%}{% if not currentparam.current%} disabled{% endif%}"><td title="{{ current.description }}, Gene: {{ current.gene }}, Protein: {{ current.channel_protein|safe }}">{{ current }}</td>
                <td>{{ currentparam.current }}{% if currentparam.current%}<br/>({{object.ion_units}}){% endif %}</td>
                <td>{{ currentparam.hill_coefficient}}</td>
                <td>{{ currentparam.saturation_level }}</td>
                <td>{{ currentparam.spread_of_uncertainty }}</td>
            {% endfor %}
          </tbody>
        </table>
        {%if object.notes %}
        <br/><div><label>Notes</label>
           <div class="markdowrenderview">
             <textarea class="markdownsource">{{object.notes | safe}}</textarea>
           </div>
        </div>{% endif %}
      <span id="version_info">
      </span>
      {% if object.api_errors %}<br/><div><label>API errors </label></div><br/><div> {{ object.api_errors }}</div>{% endif %}
       <div id="messages-container" class="hide-messages"><div><br/><label>AP Predict messages </label></div><br/><div id="messages"></div></div>

  </fieldset>

  </div>
  <div class="column">
    <div class="row">
        <div class="graph-column">
            <fieldset><legend><button type="button" class="graph-button" id="pkpd_results" style="display: none;">PKPD - APD90 vs. Timepoint</button><button type="button" class="graph-button" id="adp90" style="display: none;">Δ APD90 vs. Conc</button><button type="button" class="graph-button" id="qnet" style="display: none;">qNet vs. Conc</button></legend>
              <div class="zoom-msg">Zoom in by selecting a region.</div>
              <div id="pkpd_results-graph" class="data-graph show-graph"></div>
              <div id="adp90-graph" class="data-graph hide-graph"></div>
              <div id="qnet-graph" class="data-graph hide-graph"></div>

            </fieldset>
        </div>
        <div class="control-column">
            <div class="control-items">
                <div id="qnetSource"><p><label>Source</label></p></div>
                <div id="legendContainerpkpd_results" class="legend"></div>
                <div id="legendContainerQnet">
                    <div><span id="qnet-colour">&nbsp;&nbsp;</span>&nbsp;&nbsp;<span id="qnet-series-name"></span></div>
                    <div id="confidence-percentages" class="hide-messages"><br/><label>Confidence intervals:</label><br/></div>
                </div>
                <br/><button type="button" id="resetqnet">Reset zoom</button>
                <div id="hoverdata"><p><label>Conc.:</label>  µM</p><p><label>Δ APD90: </label> %</p></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="graph-column">
            <fieldset><legend><button type="button" class="graph-button" id="vTracesButton" disabled>Voltage Traces</button></legend>
              <div class="zoom-msg">Zoom in by selecting a region.</div>
              <div id="traces-graph" class="data-graph"></div>
            </fieldset>
        </div>
        <div class="control-column">
            <div id="voltagTraces"><p><label>Simulation and Concentration (µM)</label></p></div>
            <div id="legendContainerTraces" class="legend"></div>
            <button type="button" id="resetTraces">Reset zoom</button>
            <div id="hoverdataTraces"><p><label>Time: </label> ms</p><p><label>Membrane Voltage: </label> mV</p></div>
        </div>
    </div>
  </div>
</div>
<div id='tooltip'></div>
</section>

{% endblock content %}