client/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, re_path
from django.views.generic import TemplateView
from onfig.view import MediaView


media_path = settings.MEDIA_URL.replace(settings.FORCE_SCRIPT_NAME, '')
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    re_path(r'^contact$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    re_path(r'^privacy$', TemplateView.as_view(template_name='privacy.html'), name="privacy"),

    # protected file upload
    re_path(r'^' + media_path + '(?P<file_name>.+)$', MediaView.as_view(), name="media"),

    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^files/', include('files.urls', namespace='files')),
    re_path(r'^simulations/', include('simulations.urls', namespace='simulations')),
]

client/files/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^models$',
        views.CellmlModelListView.as_view(),
        name='model_list',
    ),

    re_path(
        r'^models/new$',
        views.CellmlModelCreateView.as_view(),
        name='create_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/edit$',
        views.CellmlModelUpdateView.as_view(),
        name='edit_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)$',
        views.CellmlModelDetailView.as_view(),
        name='model_detail',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/delete$',
        views.CellmlModelDeleteView.as_view(),
        name='delete_model',
    ),

]
app_name = 'files'

client/files/forms.py
from datetime import datetime

import magic
from braces.forms import UserKwargModelFormMixin
from cellmlmanip import load_model
from django import forms
from django.core.files.uploadedfile import TemporaryUploadedFile, UploadedFile

from .models import AppredictLookupTableManifest, CellmlModel, IonCurrent


OXMETA = 'https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#'


class CellmlModelForm(forms.ModelForm, UserKwargModelFormMixin):
    class Meta:
        model = CellmlModel
        exclude = ('author', )
        widgets = {'cellml_file': forms.ClearableFileInput(attrs={'accept': '.cellml'}),
                   'year': forms.widgets.Select(choices=[(y, y) for y in range(datetime.now().year + 1, 1949, - 1)])}

    def __init__(self, *args, **kwargs):
        self.current_title = None  # current title
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        self.fields['year'].initial = datetime.now().year
        for _, field in self.fields.items():
            field.widget.attrs['title'] = field.help_text.replace('<em>', '').replace('</em>', '')

        if not self.user.is_superuser:
            self.fields.pop('model_name_tag')
            self.fields.pop('predefined')
            self.fields.pop('ap_predict_model_call')
            self.fields.pop('ion_currents')

    def clean(self):
        cleaned_data = super().clean()
        if hasattr(self, 'cellmlmanip_model'):
            cleaned_data['model_name_tag'] = self.cellmlmanip_model.name

        if 'model_name_tag' in cleaned_data:
            lut_manifest = AppredictLookupTableManifest.get_manifest()
            if not self.user.is_superuser and cleaned_data['model_name_tag'] in lut_manifest:
                raise forms.ValidationError('You have uploaded a CellML model with name tag: '
                                            f'{cleaned_data["model_name_tag"]} this tag is reserved for lookup table '
                                            'pruposes and models with this name can only be uploaded by admins.')

            models_with_name_tag = CellmlModel.objects.filter(model_name_tag=cleaned_data['model_name_tag'],
                                                              author=self.user)
            predef_models_with_name_tag = CellmlModel.objects.filter(model_name_tag=cleaned_data['model_name_tag'],
                                                                     predefined=True)

            if self.instance and self.instance.pk is not None:
                models_with_name_tag = models_with_name_tag.exclude(pk=self.instance.pk)
                predef_models_with_name_tag = predef_models_with_name_tag.exclude(pk=self.instance.pk)
            if models_with_name_tag.union(predef_models_with_name_tag):
                raise forms.ValidationError(f'A CellML model with the model name tag {cleaned_data["model_name_tag"]} '
                                            'exsists, the model name tag must be unique!')
        return cleaned_data

    def clean_name(self):
        name = self.cleaned_data['name']
        models_with_name = CellmlModel.objects.filter(name=name, author=self.user)
        predef_models_with_name = CellmlModel.objects.filter(name=name, predefined=True)

        if self.instance and self.instance.pk is not None:
            models_with_name = models_with_name.exclude(pk=self.instance.pk)
            predef_models_with_name = predef_models_with_name.exclude(pk=self.instance.pk)
        if models_with_name.union(predef_models_with_name):
            raise forms.ValidationError('A CellML model with this name esists, the name must be unique!')

        return name

    def clean_ap_predict_model_call(self):
        model_call = self.cleaned_data.get('ap_predict_model_call', None)
        if model_call and model_call.lower().strip().startswith('--model'):
            raise forms.ValidationError("Ap predict model call should not include the --model flag")

        return self.cleaned_data['ap_predict_model_call']

    def clean_cellml_file(self):
        cellml_file = self.cleaned_data.get('cellml_file', None)
        model_call = self.cleaned_data.get('ap_predict_model_call', None)

        if cellml_file is False:  # treat clearing file the same as no entry for file
            cellml_file = None

        if not self.user.is_superuser and cellml_file is None:
            raise forms.ValidationError("A cellml file is required!")

        if (model_call is None) == (cellml_file is None):  # Need either a file or model call
            raise forms.ValidationError("Either a cellml file or an Ap Predict call is required!")

        # check mime type of any uploaded file (should be XML)
        if cellml_file and isinstance(cellml_file, UploadedFile):
            mime_type = str(magic.from_buffer(cellml_file.file.read(), mime=True))
            if mime_type not in ['text/xml', 'application/xml']:
                raise forms.ValidationError('Unsupported file type, expecting a cellml file.')

        if cellml_file and isinstance(cellml_file, TemporaryUploadedFile):
            # parse file and look for ion current metadata (can only read files, not from memory)
            try:
                self.cellmlmanip_model = load_model(cellml_file.temporary_file_path())
            except Exception as e:
                raise forms.ValidationError('Could not process cellml model: \n    ' + str(e))
        return self.cleaned_data['cellml_file']

    def save(self, **kwargs):
        model = super().save(commit=False)
        if not hasattr(model, 'author') or model.author is None:
            model.author = self.user
        model.save()

        # If a cellml file was uploaded and parse, check it for metadata tags
        if hasattr(self, 'cellmlmanip_model'):
            model.ion_currents.clear()
            for current in IonCurrent.objects.all():
                for metadata_tag in [tag.strip() for tag in current.metadata_tags.split(',')]:
                    try:
                        self.cellmlmanip_model.get_variable_by_ontology_term((OXMETA, metadata_tag))
                        model.ion_currents.add(current)
                    except KeyError:
                        pass  # model does not have current)

        model.save()
        return model

client/files/views.py
from braces.views import UserFormKwargsMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import CellmlModelForm
from .models import CellmlModel


class CellmlModelListView(LoginRequiredMixin, ListView):
    """
    List all visible CellML models
    """
    template_name = 'files/cellmlmodel_list.html'

    def get_queryset(self):
        return CellmlModel.objects.filter(predefined=True) | \
            CellmlModel.objects.filter(predefined=False, author=self.request.user)


class CellmlModelCreateView(LoginRequiredMixin, UserFormKwargsMixin, CreateView):
    """
    Create a new CellML model
    """
    model = CellmlModel
    form_class = CellmlModelForm
    template_name = 'files/cellmlmodel.html'
    success_url = reverse_lazy('files:model_list')


class CellmlModelUpdateView(LoginRequiredMixin, UserPassesTestMixin, UserFormKwargsMixin, UpdateView):
    """
    Update a CellML model
    """
    model = CellmlModel
    form_class = CellmlModelForm
    template_name = 'files/cellmlmodel.html'
    success_url = reverse_lazy('files:model_list')

    def test_func(self):
        return self.get_object().author == \
            self.request.user or (self.get_object().predefined and self.request.user.is_superuser)


class CellmlModelDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """
    View a CellML model
    """
    model = CellmlModel
    template_name = 'files/cellmlmodel_detail.html'

    def test_func(self):
        return self.get_object().author == self.request.user or self.get_object().predefined


class CellmlModelDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Delete a CellML model
    """
    model = CellmlModel
    # Raise a 403 error rather than redirecting to login,
    # if the user doesn't have delete permissions.
    raise_exception = True

    def test_func(self):
        return self.get_object().author == \
            self.request.user or (self.get_object().predefined and self.request.user.is_superuser)

    def get_success_url(self, *args, **kwargs):
        ns = self.request.resolver_match.namespace
        return reverse_lazy(ns + ':model_list')

client/templates/files/cellmlmodel.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% if object.id %}Edit annotated CellML model: {{ object }} - {% else %}Create annotated CellML model - {% endif %}{% endblock title %}

{% block content %}
<div id='cellmlmodelform'>
{% with in_edit='true' %}
  {% include "./cellmlmodel_header.html" %}
{% endwith %}

  <form method="POST" action="" enctype="multipart/form-data" name="cellmlform">
    {% csrf_token %}

    {{ form.as_p }}
    <p>
    <button id="savebutton" type="submit">Save</button>
    <button class="button" id="backbutton" title="Cancel">Cancel</button>
    </p>
  </form>
</div>
{% endblock content %}

client/templates/files/cellmlmodel_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete CellML model{% endblock title %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p><strong>This operation cannot be undone.</strong></p>
    <button>Confirm</button>
    <button class="button" id="backbutton" title="Cancel">Cancel</button>
</form>

{% endblock %}

client/templates/files/cellmlmodel_detail.html
{% extends "base.html" %}

{% block title %}CellML model - {{ object }}{% endblock title %}

{% block content %}
<div id='cellmlmodeldetail'>
{% include "./cellmlmodel_header.html" %}
  <table>
    <tr><td><strong>Name:</strong></td><td>{{ object.name }}</td></tr>
    <tr><td><strong>Model name tag:</strong></td><td>{{ object.model_name_tag }}</td></tr>
    <tr><td><strong>Version: </strong></td><td>{{ object.version }}</td></tr>
    <tr><td><strong>Year: </strong></td><td>{{ object.year }}</td></tr>
    <tr><td><strong>CellMl_link: </strong></td><td><a href="{{ object.cellml_link }}" target="_blank">{% if object.cellml_link %}{{ object.cellml_link }} {% endif %}</a></td></tr>
    <tr><td><strong>Paper link: </strong></td><td><a href="{{ object.paper_link }}" target="_blank">{% if object.paper_link %}{{ object.paper_link }} {% endif %}</a></td></tr>
    <tr><td><strong>Created by: </strong></td><td>{{ object.author.full_name }}</td></tr>
    <tr><td><strong>Created at at: </strong></td><td>{{ object.created_at }}</td></tr>
    {% if object.ap_predict_model_call %}<tr><td><strong>Ap Predict call:</strong></td><td><em>--model</em> {{ object.ap_predict_model_call }}</td></tr>{% endif %}
    {% if object.cellml_file %}<tr><td><strong>CellML file:</strong></td><td><a href="{{ object.cellml_file.url }}">{{ object.cellml_file }}</a></td></tr>{% endif %}
   <tr><td><strong>Ion currents: </strong></td><td>{% for current in object.ion_currents.all %}{% if not forloop.first %}, {% endif %}{{current}}{% endfor %}</td></tr>
  </table>
   <button class="button" id="backbutton" title="Cancel">Close</button>

</div>
{% endblock content %}

client/templates/files/cellmlmodel_header.html
{% load static %}
{% load ap_nimbus %}

{% if object.id %}
<a href="{% url 'files:model_detail' object.id %}"><h1 id="entityname">Annotated CellML model: {{ object.name }}.</h1></a>
<div class="suppl">
    <small>Created <time>{{object.created_at}}</time> by <em>{{object.author.full_name}}</em>.
        {% can_edit object as can_edit %}
        {% if can_edit %}
          <a title="Delete this CellML model" href="{% url 'files:delete_model' object.id %}" title="Delete this CellML model">
            <img src="{% static 'images/delete.png' %}" alt="Delete"/>
            Delete
          </a> |
          {%if not in_edit %}
            <a title="Edit this CellML model" href="{% url 'files:edit_model' object.id %}" title="Edit this CellML model">
            <img src="{% static 'images/edit.png' %}" alt="Edit"/>
              Edit
            </a> |
          {% endif %}
        {% endif %}</small>
</div>
{% else %}<h1>Create annotated CellML model.</h1>{% endif %}

client/templates/files/cellmlmodel_list.html
{% extends "base.html" %}

{% block title %}Cellml models - {% endblock title %}

{% block content %}
  <section id="modellist">
    <h1>CellML models</h1>
    <a href="{% url 'files:create_model' %}">Upload a new Model</a>

    <h2>Predefined models</h2>

    <ul>
      {% for model in object_list %}
        {% if model.predefined %}
          <li title="{{ model.name }}">
              <a href="{% url 'files:model_detail' model.pk %}"><strong>{{ model }}</strong></a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>

    <h2>Uploaded models</h2>

    <ul>
      {% for model in object_list %}
        {% if not model.predefined %}
          <li title="{{ model.name }}">
              <a href="{% url 'files:model_detail' model.pk %}"><strong>{{ model }}</strong> (by {{model.author.full_name}})</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>

{% endblock content %}

client/templates/files/model_list.html
{% extends "base.html" %}

{% block title %}Cellml models - {% endblock title %}

{% block content %}
  <section id="modellist">
    <h1>CellML models</h1>
    <a href="{% url 'files:create_model' %}">Upload a new Model</a>

    <h2>Moderated models</h2>

    <ul>
      {% for model in object_list %}
        {% if model.visibility == 'moderated' %}
          <li title="{{ model.name }}">
              <a class="storylink" href=""><strong>{{ model.name }}{% if model.version %} {{ model.version }} {% endif %} {{ model.year }}</strong></a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>

    <h2>Uploaded models</h2>

    <ul>
      {% for model in object_list %}
        {% if model.visibility != 'moderated' %}
          <li title="{{ model.name }}">
              <a class="storylink" href="{% url 'files:model_detail' model.pk %}"><strong>{{ model.name }}{% if model.version %} {{ model.version }} {% endif %} {{ model.year }}</strong></a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>

{% endblock content %}