client/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^login/$',
        auth_views.LoginView.as_view(),
        name='login',
    ),

    re_path(
        r'^register/$',
        views.RegistrationView.as_view(),
        name='register',
    ),

    re_path(
        r'^myaccount/$',
        views.MyAccountView.as_view(),
        name='myaccount',
    ),

    re_path(
        r'^(?P<pk>\d+)/delete/$',
        views.UserDeleteView.as_view(),
        name='delete',
    ),

]

app_name = 'accounts'

client/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, re_path
from django.views.generic import TemplateView
from onfig.view import MediaView


media_path = settings.MEDIA_URL.replace(settings.FORCE_SCRIPT_NAME, '')
urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    re_path(r'^contact$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    re_path(r'^privacy$', TemplateView.as_view(template_name='privacy.html'), name="privacy"),

    # protected file upload
    re_path(r'^' + media_path + '(?P<file_name>.+)$', MediaView.as_view(), name="media"),

    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^files/', include('files.urls', namespace='files')),
    re_path(r'^simulations/', include('simulations.urls', namespace='simulations')),
]

client/files/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^models$',
        views.CellmlModelListView.as_view(),
        name='model_list',
    ),

    re_path(
        r'^models/new$',
        views.CellmlModelCreateView.as_view(),
        name='create_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/edit$',
        views.CellmlModelUpdateView.as_view(),
        name='edit_model',
    ),
    re_path(
        r'^models/(?P<pk>\d+)$',
        views.CellmlModelDetailView.as_view(),
        name='model_detail',
    ),
    re_path(
        r'^models/(?P<pk>\d+)/delete$',
        views.CellmlModelDeleteView.as_view(),
        name='delete_model',
    ),

]
app_name = 'files'

client/simulations/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r'^$',
        views.SimulationListView.as_view(),
        name='simulation_list',
    ),


    re_path(
        r'^new$',
        views.SimulationCreateView.as_view(),
        name='create_simulation',
    ),

    re_path(
        r'^(?P<pk>\d+)/edit$',
        views.SimulationEditView.as_view(),
        name='simulation_edit',
    ),

    re_path(
        r'^(?P<pk>\d+)/template$',
        views.SimulationCreateView.as_view(),
        name='simulation_template',
    ),

    re_path(
        r'^(?P<pk>\d+)/result$',
        views.SimulationResultView.as_view(),
        name='simulation_result',
    ),

    re_path(
        r'^(?P<pk>\d+)/version$',
        views.SimulationVersionView.as_view(),
        name='simulation_version',
    ),

    re_path(
        r'^(?P<pk>\d+)/delete$',
        views.SimulationDeleteView.as_view(),
        name='simulation_delete',
    ),

    re_path(
        r'^(?P<pk>\d+)/restart$',
        views.RestartSimulationView.as_view(),
        name='simulation_restart',
    ),
    re_path(
        r'^status/(?P<update>(\w+))(?P<pks>(/\d+){1,})(?:/)?$',
        views.StatusSimulationView.as_view(),
        name='simulation_status',
    ),
    re_path(
        r'^(?P<pk>\d+)/data$',
        views.DataSimulationView.as_view(),
        name='simulation_data',
    ),
    re_path(
        r'^(?P<pk>\d+)/spreadsheet$',
        views.SpreadsheetSimulationView.as_view(),
        name='simulation_spreadsheet',
    ),

]
app_name = 'simulations'

client/templates/includes/head.html
{% load static %}
<meta charset="utf-8" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
<link rel="stylesheet" href="{% static 'css/style-min.css' %}" />
<script type="text/javascript" src="{% static 'build/js/main-min.js' %}"></script>

client/templates/includes/navbar.html
<nav>
  <ul class="navbar">
    <li><a href="{% url 'home' %}" id="home_link">Home</a></li>
    {% if user.is_authenticated %}
        <li class="navbar-submenu">
          <a href="{% url 'simulations:simulation_list' %}">Simulations</a>
          <ul>
              <li><a href="{% url 'simulations:create_simulation' %}">New Simulation</a></li>
              <li><a href="{% url 'simulations:simulation_list' %}">Simulation Results</a></li>
          </ul>
        </li>
        <li class="navbar-submenu">
          <a href="{% url 'files:model_list' %}">Cellml Models</a>
        </li>
        <li class="navbar-submenu">
          <a href="{% url 'accounts:myaccount' %}">{{ user.full_name }}</a>
          <ul>
            <li><a href="{% url 'accounts:myaccount' %}">Account</a></li>
            {% if user.is_superuser %}
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
        </li>
    {% else %}
      <li><a href="{% url 'accounts:login' %}?next={{ request.path }}">Log in</a></li>
      {% if not AP_PREDICT_LDAP %}
        <li><a href="{% url 'accounts:register' %}">Register</a></li>
      {% endif %}
    {% endif %}
  </ul>
</nav>